const alphabetData =
  [
    { value: 'A', label: 'A', selected: false },
    { value: 'B', label: 'B', selected: false },
    { value: 'C', label: 'C', selected: false },
    { value: 'D', label: 'D', selected: false },
    { value: 'E', label: 'E', selected: false },
    { value: 'F', label: 'F', selected: false },
    { value: 'G', label: 'G', selected: false },
    { value: 'H', label: 'H', selected: false },
    { value: 'I', label: 'I', selected: false },
    { value: 'J', label: 'J', selected: false },
    { value: 'K', label: 'K', selected: false },
    { value: 'L', label: 'L', selected: false },
    { value: 'M', label: 'M', selected: false },
    { value: 'N', label: 'N', selected: false },
    { value: 'O', label: 'O', selected: false },
    { value: 'P', label: 'P', selected: false },
    { value: 'Q', label: 'Q', selected: false },
    { value: 'R', label: 'R', selected: false },
    { value: 'S', label: 'S', selected: false },
    { value: 'T', label: 'T', selected: false },
    { value: 'U', label: 'U', selected: false },
    { value: 'V', label: 'V', selected: false },
    { value: 'W', label: 'W', selected: false },
    { value: 'X', label: 'X', selected: false },
    { value: 'Y', label: 'Y', selected: false },
    { value: 'Z', label: 'Z', selected: false }
  ]

const questionsData = [
  { id: 1, label: 'Frutas', selected: false },
  { id: 2, label: 'Capitales de países', selected: false },
  { id: 3, label: 'Colores', selected: false },
  { id: 4, label: 'Animales', selected: false },
  { id: 5, label: 'Deportes', selected: false },
  { id: 6, label: 'Cantantes', selected: false },
  { id: 7, label: 'Instrumentos musicales', selected: false },
  { id: 8, label: 'Películas', selected: false },
  { id: 9, label: 'Marcas en general', selected: false },
  { id: 10, label: 'Partes del cuerpo', selected: false },
  { id: 11, label: 'Objetos de una casa', selected: false },
  { id: 12, label: 'Comidas', selected: false },
  { id: 13, label: 'Bebidas', selected: false },
  { id: 14, label: 'Peliculas animadas', selected: false },
  { id: 15, label: 'Profesiones', selected: false },
  { id: 16, label: 'Verduras', selected: false },
  { id: 17, label: 'Bandas musicales', selected: false },
  { id: 18, label: 'Cosas en una fiesta', selected: false },
  { id: 19, label: 'Caracteristicas de una mujer', selected: false },
  { id: 20, label: 'Juguetes', selected: false },
  { id: 21, label: 'Cosas en una escuela', selected: false },
  { id: 22, label: 'Ropa', selected: false },
  { id: 23, label: 'Nombres de mujeres', selected: false },
  { id: 24, label: 'Meses del año', selected: false },
  { id: 25, label: 'Cosas en un hospital', selected: false },
  { id: 26, label: 'Series de TV', selected: false },
  { id: 27, label: 'Superhéroes', selected: false },
  { id: 28, label: 'Nombres de hombres', selected: false },
  { id: 29, label: 'Juegos de mesa', selected: false },
  { id: 30, label: 'Caracteristicas de un hombre', selected: false },
  { id: 31, label: 'Transportes', selected: false },
  { id: 32, label: 'Animales de 4 patas', selected: false },
  { id: 33, label: 'Video juegos', selected: false },
  { id: 34, label: 'Electrodomesticos', selected: false },
  { id: 35, label: 'Libros', selected: false },
  { id: 36, label: 'Géneros musicales', selected: false },
  { id: 37, label: 'Paises', selected: false },
  { id: 38, label: 'Animales acuaticos', selected: false },
  { id: 39, label: 'Nombre de famosos', selected: false },
  { id: 40, label: 'Nombres de canciones', selected: false },
  { id: 41, label: 'Elementos de la naturaleza', selected: false },
  { id: 42, label: 'Personajes animados', selected: false },
  { id: 43, label: 'Series animadas', selected: false },
  { id: 45, label: 'Sabores de helados', selected: false },
  { id: 46, label: 'Nombres de hombres', selected: false },
  { id: 47, label: 'Acciones', selected: false },
  { id: 48, label: 'Cosas que se encuentran en una oficina', selected: false },
  { id: 50, label: 'Nombres de hombres', selected: false },
  { id: 51, label: 'Apellidos', selected: false },
  { id: 52, label: 'Cosas', selected: false },
  { id: 53, label: 'Dias de la semana', selected: false },
  { id: 54, label: 'Provincias de argentina', selected: false },
  { id: 55, label: 'Materias de escuela', selected: false },
  { id: 56, label: 'Bailes', selected: false },
  { id: 57, label: 'Idiomas', selected: false },
  { id: 58, label: 'Materiales de construccion', selected: false },
  { id: 59, label: 'Elementos de una cocina', selected: false },
  { id: 60, label: 'Minerales', selected: false },
  { id: 61, label: 'Bichos', selected: false },
  { id: 62, label: 'Productos limpieza e higiene', selected: false },
  { id: 63, label: 'Insultos', selected: false },
  { id: 64, label: 'Personajes de video juegos', selected: false },
  { id: 65, label: 'Alagos', selected: false },
  { id: 66, label: 'Materiales de una libreria', selected: false },
  { id: 67, label: 'Adejetivos', selected: false },
  { id: 68, label: 'Flora', selected: false },
];

export { alphabetData, questionsData }
