const alphabetData =
  [
    { value: 'A', label: 'A', selected: false },
    { value: 'B', label: 'B', selected: false },
    { value: 'C', label: 'C', selected: false },
    { value: 'D', label: 'D', selected: false },
    { value: 'E', label: 'E', selected: false },
    { value: 'F', label: 'F', selected: false },
    { value: 'G', label: 'G', selected: false },
    { value: 'H', label: 'H', selected: false },
    { value: 'I', label: 'I', selected: false },
    { value: 'J', label: 'J', selected: false },
    { value: 'K', label: 'K', selected: false },
    { value: 'L', label: 'L', selected: false },
    { value: 'M', label: 'M', selected: false },
    { value: 'N', label: 'N', selected: false },
    { value: 'O', label: 'O', selected: false },
    { value: 'P', label: 'P', selected: false },
    { value: 'Q', label: 'Q', selected: false },
    { value: 'R', label: 'R', selected: false },
    { value: 'S', label: 'S', selected: false },
    { value: 'T', label: 'T', selected: false },
    { value: 'U', label: 'U', selected: false },
    { value: 'V', label: 'V', selected: false },
    { value: 'W', label: 'W', selected: false },
    { value: 'X', label: 'X', selected: false },
    { value: 'Y', label: 'Y', selected: false },
    { value: 'Z', label: 'Z', selected: false }
  ]

const questionsData = [
  { id: 1, label: 'Frutas', selected: false },
  { id: 2, label: 'Capitales de países', selected: false },
  { id: 3, label: 'Colores', selected: false },
  { id: 4, label: 'Animales', selected: false },
  { id: 5, label: 'Deportes', selected: false },
  { id: 6, label: 'Ciudades', selected: false },
  { id: 7, label: 'Instrumentos musicales', selected: false },
  { id: 8, label: 'Películas', selected: false },
  { id: 9, label: 'Marcas de automóviles', selected: false },
  { id: 10, label: 'Partes del cuerpo', selected: false },
  { id: 11, label: 'Muebles de casa', selected: false },
  { id: 12, label: 'Comidas', selected: false },
  { id: 13, label: 'Bebidas', selected: false },
  { id: 14, label: 'Peliculas no animadas', selected: false },
  { id: 15, label: 'Profesiones', selected: false },
  { id: 16, label: 'Lugares turísticos', selected: false },
  { id: 17, label: 'Tipos de animales domésticos', selected: false },
  { id: 18, label: 'Cosas en una fiesta', selected: false },
  { id: 19, label: 'Aves', selected: false },
  { id: 20, label: 'Juguetes', selected: false },
  { id: 21, label: 'Cosas en una escuela', selected: false },
  { id: 22, label: 'Ropa', selected: false },
  { id: 23, label: 'Nombres de mujeres', selected: false },
  { id: 24, label: 'Meses del año', selected: false },
  { id: 25, label: 'Tipos de música', selected: false },
  { id: 26, label: 'Series de televisión', selected: false },
  { id: 27, label: 'Superhéroes', selected: false },
  { id: 28, label: 'Nombres de hombres', selected: false },
  { id: 29, label: 'Juegos de mesa', selected: false },
  { id: 30, label: 'Peliculas animacion 3D', selected: false },
  { id: 31, label: 'Ciudades famosas', selected: false },
  { id: 32, label: 'Animales de 4 patas', selected: false },
  { id: 33, label: 'Comidas típicas', selected: false },
  { id: 34, label: 'Nombres de mujeres', selected: false },
  { id: 35, label: 'Libros', selected: false },
  { id: 36, label: 'Géneros musicales', selected: false },
  { id: 37, label: 'Paises', selected: false },
  { id: 38, label: 'Animales marinos', selected: false },
  { id: 39, label: 'Marcas de ropa', selected: false },
  { id: 40, label: 'Nombres de canciones', selected: false },
  { id: 41, label: 'Elementos de la naturaleza', selected: false },
  { id: 42, label: 'Personajes de disney o pixar', selected: false },
  { id: 43, label: 'Series animadadas', selected: false },
  { id: 45, label: 'Tipos de helados', selected: false },
  { id: 46, label: 'Nombres de hombres', selected: false },
  { id: 47, label: 'Artículos para el hogar', selected: false },
  { id: 48, label: 'Cosas que se encuentran en una oficina', selected: false },
  { id: 50, label: 'Nombres de hombres', selected: false }
];

export { alphabetData, questionsData }
